### PR TITLE
chore: update Keycloak version to 26.6.3 in configuration and documen…

### LINKED ISSUE #103: Update plugin to work with keycloak 26.6.3
```
oid4vp plugin version 1.2.4 no longer works with keycloak 26.6.3
2026-06-11 10:59:37,486 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.NoSuchMethodError: 'org.keycloak.services.cors.Cors org.keycloak.services.cors.Cors.allowedOrigins(java.lang.String[])'
	at io.github.adorsysgis.keycloak.protocol.oid4vc.oid4vp.service.CorsService.forWebOrigins(CorsService.java:55)
	at io.github.adorsysgis.keycloak.protocol.oid4vc.oid4vp.OID4VPUserAuthEndpoint.getAuthorizationContextState(OID4VPUserAuthEndpoint.java:207)
```

Hint:
allowedOrigins method was renamed to checkAllowedOrigins
https://github.com/keycloak/keycloak/pull/48915/files#diff-184136cf758dbb3dadd8b621d917cb38dc4f825a442a1a4cab4964c27bbeb91c

ETA: 1 hour

### PR DESCRIPTION
**Pull request by age-77**
…tation, updated CorsService

### CODE REVIEW

**Review by IngridPuppet — APPROVED** [review]

**Comment by IngridPuppet** [comment]
Thank you @age-77.
